#=========================================================================
# ASIC Design Kit -- SkyWater130
#=========================================================================
# Author : Priyanka Raina
# Date   : August 15, 2020
#

name: skywater-130nm

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - adk

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  # Set up the outputs
  - mkdir -p outputs && cd outputs
  - ln -sf ../{adk_view} adk

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  adk: skywater-130nm
  adk_view: view-standard

#-------------------------------------------------------------------------
# Special mflowgen tags
#-------------------------------------------------------------------------

sandbox: True


