#=========================================================================
# ASIC Design Kit -- SkyWater130
#=========================================================================
# Author : Priyanka Raina
# Date   : August 15, 2020
#

name: skywater-130nm

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - adk

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  # When used to harden macros that are to be used with openlane, the 
  # the maximum metal routing layer must be changed
  - if [[ x{adk_view} == xview-openlane ]]; then
      python3 ./change_max_routing_layer.py;
    fi
  - mkdir -p outputs && cd outputs
  - ln -sf ../view-standard adk

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  adk: skywater-130nm
  adk_view: view-standard

#-------------------------------------------------------------------------
# Special mflowgen tags
#-------------------------------------------------------------------------

sandbox: True


